### ISSUE TITLE
[Feature request] Add a static property with the connection status

### ISSUE THREAD

**Issue by Clearmist** [lucksoft-yungui/luck-node-mtp#2]
Right now the API is entirely methods. Would it be possible to add a boolean property containing the connection status?

## Example

```javascript
import mtp from 'luck-node-mtp';

mpt.connect();

if (mtp.connected) {
  ...
}
```

**Comment by lucksoft-yungui** [comment]
Since this project is a technical aspect of our company's non-core business, it hasn't undergone regular maintenance. Each modification consumes our limited time resources. Additionally, the logic of this project isn't overly complex, and it's possible to branch it for personal feature additions. Of course, submitting a pull request would be even more appreciated. Thank you for your understanding.
